version: '3'
services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eum
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --general-log=1
      - --general-log-file=/var/log/mysql/general.log
#    volumes:
#      - mysql-data:/var/lib/mysql2R

    networks:
      - eum-test
  redis-docker:
    image: redis:latest
    command: redis-server --port 6379
    container_name: "docker-redis"
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    networks:
      - eum-test
networks:
  eum-test:
#volumes:
#  mysql-data:
